In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('NB.csv',  encoding = 'ISO-8859-1')

In [3]:
df.head()

   type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or å£10,000...
4  spam  okmail: Dear Dave this is your final notice to...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5559 entries, 0 to 5558
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   type    5559 non-null   object
 1   text    5559 non-null   object
dtypes: object(2)
memory usage: 87.0+ KB

In [5]:
df['type'].value_counts()

ham     4812
spam     747
Name: type, dtype: int64

In [6]:
import string
from nltk.corpus import stopwords
stp = stopwords.words('english')
stp

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [7]:
import re

In [8]:
import nltk
from nltk.stem import WordNetLemmatizer as wnl

In [9]:
import sklearn
pd.set_option('max_colwidth', 1000)

In [10]:
df.head()

,type,text
0,ham,Hope you are having a good week. Just checking in
1,ham,K..give back my thanks.
2,ham,Am also doing in cbe only. But have to pay.
3,spam,"complimentary 4 STAR Ibiza Holiday or å£10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+"
4,spam,okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm

In [11]:
nltk.download('wordnet')
def clean_text(text):
    data = [char for char in text if char not in string.punctuation]
    data = ''.join(data)
    words = re.sub(r"(@[A-Za-z0-9]+)|([^A-Za-z0-9 \t])|(\w+:\/\/\S+)|^rt|http.+?", " ", data )
    words = words.lower()
    final_words = [wnl().lemmatize(word, pos="v") for word in words.split()]
    final_words = ' '.join(final_words)
    return final_words

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [12]:
df['clean_data'] = df['text'].apply(clean_text)

In [13]:
df.head()

,type,text,clean_data
0,ham,Hope you are having a good week. Just checking in,hope you be have a good week just check in
1,ham,K..give back my thanks.,kgive back my thank
2,ham,Am also doing in cbe only. But have to pay.,be also do in cbe only but have to pay
3,spam,"complimentary 4 STAR Ibiza Holiday or å£10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+",complimentary 4 star ibiza holiday or 10000 cash need your urgent collection 09066364349 now from landline not to lose out box434sk38wp150ppm18
4,spam,okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm,okmail dear dave this be your final notice to collect your 4 tenerife holiday or 5000 cash award call 09061743806 from landline tcs sae box326 cw25wx 150ppm

In [14]:
x = str(df['text'][3])
x

'complimentary 4 STAR Ibiza Holiday or å£10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+'

In [15]:
clean_text(x)

'complimentary 4 star ibiza holiday or 10000 cash need your urgent collection 09066364349 now from landline not to lose out box434sk38wp150ppm18'

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv = CountVectorizer()
bag_words = cv.fit(df['clean_data'])

In [18]:
bag_words.get_feature_names()

['008704050406',
 '0089my',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '020603',
 '0207',
 '02070836089',
 '02072069400',
 '02073162414',
 '02085076972',
 '020903',
 '021',
 '050703',
 '0578',
 '06',
 '060505',
 '061104',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '071104',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '0784987',
 '0789xxxxxxx',
 '0794674629107880867867',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18s',
 '0870',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08702840625comuk',
 '08704439680',
 '08704439680tscs',
 '08706091795',
 '0870737910216yrs',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0870k',
 '087104711148',
 '08712101358',
 '08712103738',
 '0871212025016',
 '08712300220',
 '087123002209am7pm',
 '08712317606',
 '08712400200',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402902',
 '08712402972',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712460324nat',
 '08712466669',
 '0871277810710pmin',
 '0871277810810',
 '0871277810910pmin',
 '087143423992stop',
 '087147123779am7pm',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714712412',
 '08714714011',
 '08714719523',
 '08715203028',
 '08715203649',
 '08715203652',
 '08715203656',
 '08715203677',
 '08715203685',
 '08715203694',
 '08715205273',
 '08715500022',
 '08715705022',
 '08717111821',
 '08717168528',
 '08717205546',
 '08717507382',
 '08717507711',
 '08717509990',
 '08717890890',
 '08717895698',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '08718726270150gbpmtmsg18',
 '08718726970',
 '08718726971',
 '08718726978',
 '087187272008',
 '08718727868',
 '08718727870',
 '08718729755',
 '08718729758',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180219',
 '08719180248',
 '08719181259',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899217',
 '08719899229',
 '08719899230',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000460',
 '09050000555',
 '09050000878',
 '09050000928',
 '09050001295',
 '09050001808',
 '09050002311',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058091870',
 '09058094454',
 '09058094455',
 '09058094507',
 '09058094565',
 '09058094583',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701851',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061744553',
 '09061749602',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142stopsms08',
 '09065171142stopsms08718727870150ppm',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368327',
 '09066368470',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066649731from',
 '09066660100',
 '09071512432',
 '09071512433',
 '09071517866',
 '09077818151',
 '09090204448',
 '09090900040',
 '09094100151',
 '09094646631',
 '09094646899',
 '09095350301',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09099726553',
 '09111030116',
 '09111032124',
 '09701213186',
 '0anetworks',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '1000call',
 '1000s',
 '100603',
 '100psms',
 '100s',
 '1010',
 '1013',
 '101mega',
 '1030',
 '10803',
 '10am',
 '10am7pm',
 '10am9pm',
 '10k',
 '10p',
 '10pmin',
 '10ppm',
 '10th',
 '11',
 '1120',
 '113',
 '1131',
 '11414',
 '1146',
 '1148',
 '116',
 '1172',
 '118pmsg',
 '11mths',
 '12',
 '120',
 '12000pes',
 '1205',
 '121',
 '1225',
 '123',
 '1230',
 '125',
 '1250',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '12price',
 '13',
 '130',
 '131004',
 '1327',
 '13404',
 '139',
 '140',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14thmarch',
 '150',
 '1500',
 '150ea',
 '150morefrmmob',
 '150msg',
 '150mtmsgrcvd18',
 '150p',
 '150pday',
 '150perweeksub',
 '150perwksub',
 '150pm',
 '150pmeg',
 '150pmin',
 '150pmmorefrommobile2bremovedmobypobox734ls27yf',
 '150pmsg',
 '150pmsgrcvd',
 '150pmsgrcvdhgsuite3422landsroww1j6hl',
 '150pmt',
 '150pmtmsg',
 '150pmtmsgrcvd18',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150ppmsg',
 '150prcvd',
 '150psms',
 '150ptext',
 '150ptone',
 '150pw',
 '150pwk',
 '150rcvd',
 '150week',
 '150wk',
 '151',
 '1526',
 '153',
 '15541',
 '15pmin',
 '16',
 '1680',
 '169',
 '16only',
 '177',
 '18',
 '180',
 '181104',
 '1843',
 '186',
 '18only',
 '18ptxt',
 '18yrs',
 '195',
 '1956669',
 '1appledayno',
 '1childish',
 '1cup',
 '1da',
 '1er',
 '1hanuman',
 '1his',
 '1hr',
 '1im',
 '1lemondayno',
 '1mcflyall',
 '1million',
 '1minmobsmore',
 '1minmobsmorelkpobox177hp51fl',
 '1minmoremobsemspobox45po139wa',
 '1month',
 '1pm',
 '1s',
 '1st',
 '1st4terms',
 '1stchoicecouk',
 '1stone',
 '1tulsi',
 '1u',
 '1unbreakable',
 '1winaweek',
 '1winawk',
 '1x150pwk',
 '1yf',
 '20',
 '200',
 '2000',
 '20000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2025050',
 '20f',
 '20m12aq',
 '20p',
 '20pmin',
 '21',
 '211104',
 '215',
 '21870000hi',
 '21m',
 '21st',
 '22',
 '220cm2',
 '23',
 '2309',
 '230ish',
 '24',
 '241',
 '241004',
 '247mp',
 '24hrs',
 '24m',
 '24th',
 '25',
 '250',
 '250k',
 '255',
 '25f',
 '25p',
 '260305',
 '261004',
 '261104',
 '2667',
 '26th',
 '2703',
 '27603',
 '28',
 '2814032',
 '285',
 '28days',
 '28th',
 '28thfebtcs',
 '290305',
 '29100',
 '29m',
 '2b',
 '2bajarangabali',
 '2bold',
 '2c',
 '2channel',
 '2day',
 '2daylove',
 '2docdplease',
 '2end',
 '2exit',
 '2ez',
 '2getha',
 '2geva',
 '2go',
 '2godid',
 '2gthr',
 '2hook',
 '2hrs',
 '2i',
 '2im',
 '2kbsubject',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2morrowxxxx',
 '2mro',
 '2mrw',
 '2mwen',
 '2naughty',
 '2nd',
 '2nhite',
 '2nights',
 '2nite',
 '2nitetell',
 '2optout',
 '2optoutd3wv',
 '2p',
 '2police',
 '2px',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2u2',
 '2untamed',
 '2watershd',
 '2waxsto',
 '2when',
 '2wks',
 '2wt',
 '2wu',
 '2years',
 '2yr',
 '2yrs',
 '30',
 '300',
 '3000',
 '300603',
 '300603tcsbcm4235wc1n3xxcallcost150ppmmobilesvary',
 '300p',
 '3030',
 '30apr',
 '30pptxt',
 '30s',
 '30th',
 '31',
 '3100',
 '310303',
 '311004',
 '31pmsg150p',
 '32000',
 '3230',
 '32323',
 '326',
 '32f',
 '330',
 '3350',
 '3365',
 '350',
 '3510i',
 '35p',
 '3650',
 '36504',
 '3680',
 '3680offer',
 '373',
 '3750',
 '375max',
 '38',
 '391784',
 '399',
 '3aj',
 '3cover',
 '3d',
 '3days',
 '3db',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3maruti',
 '3miles',
 '3mins',
 '3mobile',
 '3optical',
 '3pound',
 '3qxj9',
 '3rd',
 '3sentiment',
 '3ss',
 '3u',
 '3unkempt',
 '3uz',
 '3wife',
 '3wk',
 '3wks',
 '3x',
 '3xx',
 '40',
 '400',
 '400minscall',
 '402',
 '4041',
 '40411',
 '40533',
 '40gb',
 '40mph',
 '415',
 '41685',
 '41782',
 '420',
 '42049',
 '4217',
 '42478',
 '42810',
 '430',
 '434',
 '44',
 '4403ldnw1a7rw18',
 '447797706009',
 '447801259231',
 '447per',
 '448712404000please',
 '449050000301',
 '449071512431',
 '449month',
 '45',
 '450',
 '450p',
 '450ppw',
 '450pw',
 '45239',
 '46',
 '47',
 '4712',
 '4742',
 '48',
 '4882',
 '48922',
 '49557',
 '4a',
 '4brekkie',
 '4cook',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4got',
 '4goten',
 '4info',
 '4jx',
 '4lux',
 '4mths',
 '4my',
 '4o',
 '4pavanaputra',
 '4press',
 '4rowdy',
 '4some1',
 '4tctxt',
 '4th',
 '4the',
 '4txt',
 '4txt120p',
 '4u',
 '4ui',
 '4utxt',
 '4w',
 '4ward',
 '4wrd',
 '4years',
 '50',
 '500',
 '5000',
 '500000',
 '505060',
 '50award',
 '50p',
 '50s',
 '515',
 '515pm',
 '5226',
 '5249',
 '526',
 '528',
 '530',
 '532',
 '54',
 '542',
 '545',
 '5903',
 '5digital',
 '5free',
 '5ful',
 '5gardener',
 '5gently',
 '5i',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5month',
 '5p',
 '5pm',
 '5sankatmochan',
 '5terror',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '600',
 '6031',
 '60400thousadi',
 '60p',
 '60pmin',
 '61200',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '62735',
 '630',
 '63miles',
 '645',
 '645pm',
 '650',
 '6669',
 '67441233',
 '68866',
 '69101',
 '69200',
 '69669',
 '69696',
 '69698',
 '69855',
 '6986618',
 '69876',
 '69888',
 '69888nyt',
 '69911',
 '69969',
 '69988',
 '6cruel',
 '6days',
 '6hl',
 '6housemaid',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6pm',
 '6ramaduth',
 '6romantic',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '71',
 '725',
 '7250',
 '7250i',
 '730',
 '730ish',
 '730pm',
 '731',
 '74355',
 '750',
 '75000',
 '7548',
 '7634',
 '7684',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '78pmin',
 '79',
 '7am',
 '7cfca1a',
 '7children',
 '7ish',
 '7mahaveer',
 '7oz',
 '7pm',
 '7romantic',
 '7shy',
 '7th',
 '7ws',
 '7zs',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300pwk',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80488biz',
 '80608',
 '8077',
 '80878',
 '80s',
 '81010',
 '81151',
 '81303',
 '81618',
 '816183',
 '82242',
 '82277',
 '82277unsub',
 '82324',
 '82468',
 '830',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332please',
 '83338',
 '83355',
 '83370',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84122',
 '84128',
 '84128custcare',
 '84199',
 '84484',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '863',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '87239',
 '87575',
 '8800',
 '88039',
 '88039skilgmetscs087147403231winawkage16',
 '88066',
 '88088',
 '88222',
 '8830',
 '88600',
 '88800',
 '8883',
 '88877',
 '88877free',
 '88888',
 '89034',
 '89070',
 '89080',
 '89105',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8attractive',
 '8ball',
 '8hr',
 '8lb',
 '8lovable',
 '8neighbour',
 '8o',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '9153',
 '924',
 '92h',
 '930',
 '945',
 '946',
 '95pax',
 '96',
 '97n7qp',
 '98321561',
 '9996',
 '9ae',
 '9am',
 '9am11pm',
 '9decent',
 '9funny',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '9yt',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aaooooright',
 'aathilove',
 'aathiwhere',
 'ab',
 'abbey',
 'abdomen',
 'abeg',
 'abelu',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'about',
 'aboutas',
 'above',
 'abroad',
 'absence',
 'absolutely',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abuse',
 'abusers',
 'ac',
 'academic',
 'acc',
 'accent',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accidant',
 'accident',
 'accidentally',
 'accommodation',
 'accommodationvouchers',
 'accomodate',
 'accomodations',
 'accordin',
 'accordingly',
 'accordinglyor',
 'account',
 'accumulation',
 'achanammarakheshqatar',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'acoentry41',
 'across',
 'acsmsrewards',
 'act',
 'actin',
 'action',
 ...]

In [19]:
bag_words = bag_words.transform(df['clean_data'])

In [20]:
bag_words.shape

(5559, 8514)

In [21]:
df.shape

(5559, 3)

In [22]:
X = pd.DataFrame(data = bag_words.toarray())

In [23]:
X

,0,1,2,3,4,5,6,7,8,9,...,8504,8505,8506,8507,8508,8509,8510,8511,8512,8513
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5554,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5555,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5556,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5557,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5558,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df['type'].replace(to_replace = ['spam','ham'] , value = [1,0] , inplace = True)
y = df['type']
df['type'].value_counts()

0    4812
1     747
Name: type, dtype: int64

In [25]:
import pickle
pickle.dump(cv, open("vector_f.pkl", "wb"))
CV = pickle.load(open("vector_f.pkl", 'rb'))
CV

CountVectorizer()

In [26]:
var = df['clean_data'].iloc[3]
var  = [var]

In [27]:
var

['complimentary 4 star ibiza holiday or 10000 cash need your urgent collection 09066364349 now from landline not to lose out box434sk38wp150ppm18']

In [28]:
bag =CV.transform(var).toarray()
bag.shape

(1, 8514)

In [29]:
bag

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)
print(sss.get_n_splits(X, y))
print(sss)

train_idx = 0
test_idx = 0
for train_idx , test_idx in sss.split(X,y):
    X_train  , X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train  , y_test = y.iloc[train_idx], y.iloc[test_idx]

1
StratifiedShuffleSplit(n_splits=1, random_state=0, test_size=0.1,
            train_size=None)

In [31]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y.value_counts())
print(y_train.value_counts())
print(y_test.value_counts())

(5003, 8514)
(556, 8514)
(5003,)
(556,)
0    4812
1     747
Name: type, dtype: int64
0    4331
1     672
Name: type, dtype: int64
0    481
1     75
Name: type, dtype: int64

In [32]:
from sklearn.svm import SVC

In [33]:
clf = SVC(class_weight = 'balanced')


clf.fit(X_train, y_train)

SVC(class_weight='balanced')

In [34]:
predict = clf.predict(X_train)

In [35]:
predict

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [36]:
expected = y_train

from sklearn import metrics
print(metrics.classification_report(expected, predict))
print(metrics.confusion_matrix(expected, predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4331
           1       1.00      1.00      1.00       672

    accuracy                           1.00      5003
   macro avg       1.00      1.00      1.00      5003
weighted avg       1.00      1.00      1.00      5003

[[4329    2]
 [   2  670]]

In [37]:
predicted = clf.predict(X_test)
expected = y_test

from sklearn import metrics
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       481
           1       0.98      0.84      0.91        75

    accuracy                           0.98       556
   macro avg       0.98      0.92      0.95       556
weighted avg       0.98      0.98      0.98       556

[[480   1]
 [ 12  63]]

In [38]:
pickle.dump(clf, open("model.pkl", "wb"))
model = pickle.load(open("model.pkl", 'rb'))
model

SVC(class_weight='balanced')

In [39]:
model.predict(bag)

array([1], dtype=int64)

In [40]:
import gzip, pickle
with gzip.open('model_2.pkl', 'wb') as ofp:
    pickle.dump(clf, ofp)

In [41]:
with gzip.open('model_2.pkl', 'rb') as ifp:
    m = pickle.load(ifp)

In [42]:
m.predict(bag)

array([1], dtype=int64)

In [43]:
message  = str('okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm')
data = [message]
data_clean = clean_text(data)
data_clean = [data_clean]
vect = CV.transform(data_clean).toarray()
my_prediction = m.predict(vect)

In [44]:
my_prediction

array([1], dtype=int64)